# Book settings
title                       : Theoretical Neuroscience  # The title of the book. Will be placed in the left navbar.
author                      : Jaeho Cho  # The author of the book
copyright                   : "2025"  # Copyright year to be placed in the footer

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year

repository:
  url: https://github.com/jaehho/Theoretical-Neuroscience
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true